### ISSUE TITLE
Internal Server Error on calling lemon_markets.instrument.Instrument.list()

### ISSUE THREAD

**Issue by p3h3** [lemon-markets/lemon-markets-python-sdk#4]
Hey,
I was trying to follow along the readme and got a concerning Error message:
`lemon_markets.common.requests.ApiResponseError: An error occurred while performing the request with error code 500: 
 b'\n<!doctype html>\n<html lang="en">\n<head>\n  <title>Server Error (500)</title>\n</head>\n<body>\n  <h1>Server Error (500)</h1><p></p>\n</body>\n</html>\n'`

My code is the following (basically as provided in the readme):
`from lemon_markets.instrument import Instrument`
`instruments = Instrument.list(authorization_token=access_token)`
`print(instruments)`

My access token is valid and stored in the `access_token` string. I double checked.
Since there isn't any information in the error itself - besides that the error didn't occur on my side - I would be very thankful to see what type of error you guys have or if you could help me with it.

**Comment by p3h3** [comment]
To be a bit more precise, here is the full traceback:

Traceback (most recent call last):
  File "Project/data_entry.py", line 114, in <module>
    data_entry = DataEntry(db_helper, config.access_token)
  File "Project/data_entry.py", line 27, in __init__
    instruments = Instrument.list(authorization_token=access_token)
  File "Project\venv\lib\site-packages\lemon_markets\instrument.py", line 39, in list
    authorization_token=authorization_token)
  File "Project\venv\lib\site-packages\lemon_markets\common\objects.py", line 164, in list
    request = ApiRequest(**request_arguments)
  File "Project\venv\lib\site-packages\lemon_markets\common\requests.py", line 71, in __init__
    self._perform_request()
  File "Project\venv\lib\site-packages\lemon_markets\common\requests.py", line 95, in _perform_request
    raise e
  File "Project\venv\lib\site-packages\lemon_markets\common\requests.py", line 93, in _perform_request
    self._response = ApiResponse(content=response.content, status=response.status_code, is_success=response.ok)
  File "Project\venv\lib\site-packages\lemon_markets\common\requests.py", line 35, in __init__
    raise ApiResponseError(content, status)
`lemon_markets.common.requests.ApiResponseError: An error occurred while performing the request with error code 500: 
 b'\n<!doctype html>\n<html lang="en">\n<head>\n  <title>Server Error (500)</title>\n</head>\n<body>\n  <h1>Server Error (500)</h1><p></p>\n</body>\n</html>\n'`

**Comment by stefanhoelzl** [comment]
Seeing the same issue with `lemon_markets.data.ohlc.M1.list`
```python
>>> M1.list(instrument="DE0007100000", authorization_token=token)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/stefan/Development/fundstats/venv/lib/python3.8/site-packages/lemon_markets/data/ohlc.py", line 53, in list
    return ListMixin.list(ordering=ordering,
  File "/Users/stefan/Development/fundstats/venv/lib/python3.8/site-packages/lemon_markets/common/objects.py", line 164, in list
    request = ApiRequest(**request_arguments)
  File "/Users/stefan/Development/fundstats/venv/lib/python3.8/site-packages/lemon_markets/common/requests.py", line 71, in __init__
    self._perform_request()
  File "/Users/stefan/Development/fundstats/venv/lib/python3.8/site-packages/lemon_markets/common/requests.py", line 95, in _perform_request
    raise e
  File "/Users/stefan/Development/fundstats/venv/lib/python3.8/site-packages/lemon_markets/common/requests.py", line 93, in _perform_request
    self._response = ApiResponse(content=response.content, status=response.status_code, is_success=response.ok)
  File "/Users/stefan/Development/fundstats/venv/lib/python3.8/site-packages/lemon_markets/common/requests.py", line 35, in __init__
    raise ApiResponseError(content, status)
lemon_markets.common.requests.ApiResponseError: An error occurred while performing the request with error code 500: 
 b'\n<!doctype html>\n<html lang="en">\n<head>\n  <title>Server Error (500)</title>\n</head>\n<body>\n  <h1>Server Error (500)</h1><p></p>\n</body>\n</html>\n'
```
